version: '3.3'
services:
  percona-tookkit:
    image: perconalab/percona-toolkit
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
      - ./tmp:/tmp
    ports:
      - "3306:3306"
