# curl --location --request POST 'https://api.twitter.com/2/oauth2/token'
#--basic -u '<CLIENT_ID>:<CLIENT_SECRET>'
#--header 'Content-Type: application/x-www-form-urlencoded'
#--data-urlencode 'code=<CODE>'
#--data-urlencode 'grant_type=authorization_code'
#--data-urlencode 'redirect_uri=<REDIRECT_URI>'
#--data-urlencode 'code_verifier=challenge'
POST https://api.twitter.com/2/oauth2/token
Authorization: Basic {{CLIENT_ID}} {{CLIENT_SECRET}}
Content-Type: application/x-www-form-urlencoded

code=xxx&grant_type=authorization_code&redirect_uri=https://twitter.com/&code_verifier=aaa

###

