import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import ja_JP from 'antd/locale/ja_JP';
import '@/styles/global.scss';

export const metadata = {
  title: 'Slack Copy App',
  description: 'Generated by Next.js',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="ja">
    <body>
      <AntdRegistry>
        <ConfigProvider locale={ja_JP}>{children}</ConfigProvider>
      </AntdRegistry>
    </body>
  </html>
);

export default RootLayout;
